name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-app:${{ github.sha }} .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run tests
      run: docker run my-app:${{ github.sha }} npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker tag my-app:${{ github.sha }} mydockerhubuser/my-app:${{ github.sha }}
        docker push mydockerhubuser/my-app:${{ github.sha }}
